begin;

create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  titolo text not null,
  descrizione text,
  ingredienti jsonb not null default '[]'::jsonb,
  istruzioni text not null,
  difficolta text not null default 'Facile',
  tempo_minuti integer not null,
  tipo_pasto text not null default 'Pranzo',
  tags text[] not null default '{}',
  immagine text
);

alter table public.recipes add column if not exists descrizione text;
alter table public.recipes add column if not exists immagine text;
alter table public.recipes enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'recipes'
      and policyname = 'Public recipes are readable'
  ) then
    create policy "Public recipes are readable"
      on public.recipes
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

update public.recipes
set descrizione = case titolo
  when 'Biscotti della longevità' then 'Un biscotto intenso e naturalmente dolce, pensato per una pausa che sa davvero di buono.'
  when 'Bocconcini di tacchino in crema' then 'Tacchino tenero, cotto lentamente e avvolto da una crema saporita al lievito nutrizionale.'
  when 'Carciofi al gratin' then 'Un contorno semplice e intenso, con cuori di carciofo morbidi e una finitura dorata al lievito nutrizionale.'
  when 'Pasta cremosa al branzino e broccoli' then 'Cremosa senza essere pesante, con il branzino che rende speciale anche un pranzo feriale.'
  when 'Rigatoni al ragù di coniglio' then 'Un ragù lento, profondo e rassicurante per quando hai voglia di cucinare sul serio.'
  when 'Spaghetti integrali all’orata, pomodorini e crema di carote' then 'Pesce, pomodorini e una crema luminosa: un pranzo completo che sembra da ristorante.'
  when 'Polpette di carne e spinaci' then 'Morbide dentro, dorate fuori e abbastanza pratiche da risolvere la cena di tutti.'
  else descrizione
end
where coalesce(trim(descrizione), '') = '';

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'recipe-images',
  'recipe-images',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

commit;
